### ISSUE TITLE
[SSOv2] State parameter isn't optional

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/sso-issues#45]
If the `state` parameter isn't included in the redirect to `/v2/oauth/authorize`, the page will display an error:
```json
{
    "error": "invalid_request",
    "error_description": "The state parameter is required."
}
```
I'm not sure if this is a bug, or an intentional requirement, but I would like to have it be an optional parameter.

**Comment by baynex** [comment]
Per the v2 documentation:
"state is required by EVE's SSO to encourage extra security measures."

**Comment by CarbonAlabel** [comment]
It's a modification request, then.

If I don't find the state parameter to be useful or necessary for my use case, the most this requirement will do is annoy me a bit, and make me add a nonsense state parameter (`scope=.`), which doesn't act as any kind of security measure.

**Comment by gehnster** [comment]
> It's a modification request, then.
> 
> If I don't find the state parameter to be useful or necessary for my use case, the most this requirement will do is annoy me a bit, and make me add a nonsense state parameter (`scope=.`), which doesn't act as any kind of security measure.

Just because you want to ignore the security measure doesn't mean it should be encouraged to ignore the security measure by making it optional.

**Comment by Kyria** [comment]
Even if i understand the will of "encouraging people to be more secure", the RFC still state that the "state" parameter is **recommended**, and not "required", thus it must be optional in the use of the SSO.

**Comment by gehnster** [comment]
> Even if i understand the will of "encouraging people to be more secure", the RFC still state that the "state" parameter is **recommended**, and not "required", thus it must be optional in the use of the SSO.

I disagree, if CCP wants to require a state parameter, nonsensical or not, it is their prerogative to require it in their SSO implementation.

**Comment by baynex** [comment]
The fact is they can't **force** you to check that state when you get the callback. But they can force you to send one to them. I hadn't implemented it in V1 because I saw optional and immediately skipped it. Now that it's required in V2 I figured I might as well do it right if i'm gonna do it. 

Having the state parameter required is good for the overall security of the third-party app ecosystem due to people like me who skip optional steps, but try not to half-ass things when I do do them.

**Comment by cvweiss** [comment]
> If I don't find the state parameter to be useful or necessary for my use case

You've wasted more time creating this ticket, following up on it, and discussing it then it would have taken you to add a state=idontusethis and pass that along and then just  _ignore_ it in the callback. Just because it doesn't fit your use case doesn't mean a good security measure should be made optional.

**Comment by stebet** [comment]
The state parameter will not be made optional.
